language: node_js
node_js:
- "7"
deploy:
  provider: heroku
  api_key:
    secure: YFRNto888Ow0noR8yvwsYuuLB98FSE6axBeld18SosdDHZFaKPupqiu/Mb2/rd7m2JCdF9/lD4KeQXMNWLHTUkQVN0iefqL3dxk+wZLTLTxnxupqWx7aJWozxcGphpEeuqHWQsquwfFNjJj2UCbMX9nejNMH97ITcU6js1wDnv3sZ7oE608tqQtm/kSHmC0adCV+8wp02EAmWpWrJMe5ewFnIxCLn8mrClgIZB6Sb9Us84WC4onhdEXfeWoLaJ8PPgwZsPeIhlxcZ2FfPD0hvb8/af1ATi2js42slANKjlZZNYTPpr81J3PfcK7DnIIBK9gG0uQ/apaJkpzrzd8+AcdmW485yj3SH9YnHOu/ZGdm7/jYyqHwIm7FO5OTOyNvpN2TmbDmzjTShd0hB/yU6GgP798jcnU1Mn99deTLT6J2q1UUec025sjXhANBgEg0k4Hcj1oRrjFhq15DLTd7VQAuuSAH5IHraeHsBwWfF9NTcy8ulCt+xG/+O0hgApFjiWRYHLNLlDkEgRspN+O6ucyp4oYnei3oTeucnFL0kvncH6d046nuZaiF0Tl3sQIsPSRwgyF17e0aoA4Lw1xFm0OqlZhVHopkbzzRSAobg/zsBKiMDPUhm5AwWGe6oJzZsI768fBhQnA0WdptLjoMwxoZobq6l1I79fG9VOd6174=
  app: emissary-pseudopandas
